export const PLAYER_REGISTRY_ABI = [
  "function registerPlayer(string name, string position, string nationality, uint256 contractExpiry) external payable returns (uint256)",
  "function listPlayer(uint256 playerId, uint256 askingPrice) external payable",
  "function delistPlayer(uint256 playerId) external",
  "function verifyPlayer(uint256 playerId) external",
  "function transferClubOwnership(uint256 playerId, address newClub) external",
  "function getPlayer(uint256 playerId) external view returns (tuple(uint256 id, string name, string position, string nationality, uint256 contractExpiry, address currentClub, bool isVerified, bool isListed, uint256 askingPrice, uint256 registeredAt))",
  "function getClubPlayers(address club) external view returns (uint256[])",
  "function totalPlayers() external view returns (uint256)",
  "function registrationFee() external view returns (uint256)",
  "function listingFee() external view returns (uint256)",
  "function hasRole(bytes32 role, address account) external view returns (bool)",
  "function CLUB_ROLE() external view returns (bytes32)",
  "function REGISTRAR_ROLE() external view returns (bytes32)",
  "event PlayerRegistered(uint256 indexed playerId, string name, address indexed club)",
  "event PlayerVerified(uint256 indexed playerId, address indexed registrar)",
  "event PlayerListed(uint256 indexed playerId, uint256 askingPrice)",
  "event PlayerDelisted(uint256 indexed playerId)",
  "event ClubOwnershipTransferred(uint256 indexed playerId, address indexed fromClub, address indexed toClub)",
] as const;

export const TRANSFER_ESCROW_ABI = [
  "function createDeal(uint256 playerId, address sellingClub, address paymentToken, uint256 transferFee, uint256 sellOnBps, address sellOnRecipient) external returns (uint256)",
  "function cancelDeal(uint256 dealId) external",
  "function approveDeal(uint256 dealId) external",
  "function rejectDeal(uint256 dealId, string reason) external",
  "function claimFunds(uint256 dealId) external",
  "function withdrawClaimable(address token) external",
  "function approveToken(address token) external",
  "function getDeal(uint256 dealId) external view returns (tuple(uint256 playerId, address buyingClub, address sellingClub, address paymentToken, uint256 transferFee, uint256 sellOnBps, address sellOnRecipient, uint8 state, uint256 createdAt, uint256 approvedAt, string rejectionReason))",
  "function getClaimable(address account, address token) external view returns (uint256)",
  "function getActivePlayerDeal(uint256 playerId) external view returns (uint256)",
  "function isTokenApproved(address token) external view returns (bool)",
  "function totalDeals() external view returns (uint256)",
  "function hasRole(bytes32 role, address account) external view returns (bool)",
  "function CLUB_ROLE() external view returns (bytes32)",
  "function LEAGUE_ROLE() external view returns (bytes32)",
  "event DealCreated(uint256 indexed dealId, uint256 indexed playerId, address buyingClub, address sellingClub, uint256 transferFee)",
  "event DealApproved(uint256 indexed dealId, address indexed approver)",
  "event DealRejected(uint256 indexed dealId, address indexed approver, string reason)",
  "event DealCompleted(uint256 indexed dealId, address indexed newClub)",
  "event DealCancelled(uint256 indexed dealId)",
  "event FundsClaimed(address indexed recipient, address indexed token, uint256 amount)",
] as const;

export const LOAN_ESCROW_ABI = [
  "function createLoan(uint256 playerId, address parentClub, address paymentToken, uint256 loanFee, uint256 loanDuration, bool hasOptionToBuy, uint256 optionPrice) external returns (uint256)",
  "function cancelLoan(uint256 loanId) external",
  "function approveLoan(uint256 loanId) external",
  "function rejectLoan(uint256 loanId, string reason) external",
  "function claimLoanFee(uint256 loanId) external",
  "function requestRecall(uint256 loanId) external",
  "function executeRecall(uint256 loanId) external",
  "function settleLoanExpiry(uint256 loanId) external",
  "function exerciseOption(uint256 loanId) external",
  "function withdrawClaimable(address token) external",
  "function getLoan(uint256 loanId) external view returns (tuple(uint256 playerId, address parentClub, address borrowingClub, address paymentToken, uint256 loanFee, uint256 loanStart, uint256 loanExpiry, bool hasOptionToBuy, uint256 optionPrice, uint8 state, uint256 createdAt, uint256 approvedAt, uint256 recallRequestedAt, bool loanFeeClaimed, string rejectionReason))",
  "function getClaimable(address account, address token) external view returns (uint256)",
  "function getActivePlayerLoan(uint256 playerId) external view returns (uint256)",
  "function totalLoans() external view returns (uint256)",
  "event LoanCreated(uint256 indexed loanId, uint256 indexed playerId, address parentClub, address borrowingClub, uint256 loanFee)",
  "event LoanApproved(uint256 indexed loanId, address indexed approver)",
  "event LoanExpired(uint256 indexed loanId)",
  "event LoanRecalled(uint256 indexed loanId)",
  "event OptionExercised(uint256 indexed loanId, uint256 optionPrice)",
] as const;

export const TRANSFER_WINDOW_ABI = [
  "function isWindowOpen() external view returns (bool)",
  "function getActiveWindow() external view returns (tuple(uint256 id, string label, uint256 opensAt, uint256 closesAt, bool exists))",
  "function scheduleWindow(string label, uint256 opensAt, uint256 closesAt) external returns (uint256)",
  "function totalWindows() external view returns (uint256)",
] as const;

export const ERC20_ABI = [
  "function approve(address spender, uint256 amount) external returns (bool)",
  "function allowance(address owner, address spender) external view returns (uint256)",
  "function balanceOf(address account) external view returns (uint256)",
  "function decimals() external view returns (uint8)",
] as const;
