export const PLAYER_REGISTRY_ABI = [
  "function registerPlayer(string name, string position, string nationality, uint256 contractExpiry, uint256 weeklySalary) external payable returns (uint256)",
  "function listPlayer(uint256 playerId, uint256 askingPrice) external payable",
  "function delistPlayer(uint256 playerId) external",
  "function verifyPlayer(uint256 playerId) external",
  "function setMedicalClearance(uint256 playerId, bytes32 documentHash) external",
  "function submitLegalDocuments(uint256 playerId, bytes32 registrationContractHash, bytes32 identityDocumentHash, bytes32 fifaTMSHash, bytes32 workPermitHash) external",
  "function verifyLegalDocuments(uint256 playerId) external",
  "function setPlayerWallet(uint256 playerId, address playerWallet) external",
  "function updatePlayerWallet(uint256 playerId, address newWallet) external",
  "function setReleaseClause(uint256 playerId, uint256 amount) external",
  "function extendContract(uint256 playerId, uint256 newExpiry) external",
  "function getPlayer(uint256 playerId) external view returns (tuple(uint256 id, string name, string position, string nationality, uint256 contractExpiry, uint256 weeklySalary, address playerWallet, bool isVerified, bool isListed, bool medicalClearance, bytes32 medicalDocumentHash, uint256 askingPrice, uint256 releaseClause, uint256 registeredAt))",
  "function getLegalDocuments(uint256 playerId) external view returns (tuple(bytes32 registrationContractHash, bytes32 identityDocumentHash, bytes32 fifaTMSHash, bytes32 workPermitHash, bool documentsVerified))",
  "function getClubPlayers(address club) external view returns (uint256[])",
  "function totalPlayers() external view returns (uint256)",
  "function registrationFee() external view returns (uint256)",
  "function listingFee() external view returns (uint256)",
  "function hasRole(bytes32 role, address account) external view returns (bool)",
  "function CLUB_ROLE() external view returns (bytes32)",
  "function REGISTRAR_ROLE() external view returns (bytes32)",
  "function ownerOf(uint256 tokenId) external view returns (address)",
  "function currentClub(uint256 playerId) external view returns (address)",
] as const;

export const TRANSFER_ESCROW_ABI = [
  "function createDeal(uint256 playerId, address sellingClub, address paymentToken, uint256 transferFee, uint256 salaryGuaranteeMonths, uint256 sellOnBps, address sellOnRecipient, uint256 sellerAgentBps, address sellerAgent, uint256 buyerAgentBps, address buyerAgent, tuple(string description, uint256 amount, bool toPlayer, bool triggered)[] addOns) external returns (uint256)",
  "function cancelDeal(uint256 dealId) external",
  "function approveDeal(uint256 dealId) external",
  "function rejectDeal(uint256 dealId, string reason) external",
  "function claimFunds(uint256 dealId) external",
  "function triggerAddOn(uint256 dealId, uint256 addOnIndex) external",
  "function claimSalaryGuarantee(uint256 dealId) external",
  "function withdrawClaimable(address token) external",
  "function approveToken(address token) external",
  "function getDeal(uint256 dealId) external view returns (tuple(uint256 playerId, address buyingClub, address sellingClub, address paymentToken, uint256 transferFee, uint256 salaryGuaranteeMonths, uint256 salaryGuaranteeAmount, bool salaryGuaranteeClaimed, uint256 sellOnBps, address sellOnRecipient, uint256 sellerAgentBps, address sellerAgent, uint256 buyerAgentBps, address buyerAgent, uint8 state, uint256 createdAt, uint256 approvedAt, string rejectionReason))",
  "function getDealAddOns(uint256 dealId) external view returns (tuple(string description, uint256 amount, bool toPlayer, bool triggered)[])",
  "function getClaimable(address account, address token) external view returns (uint256)",
  "function getActivePlayerDeal(uint256 playerId) external view returns (uint256)",
  "function isTokenApproved(address token) external view returns (bool)",
  "function totalDeals() external view returns (uint256)",
  "function hasRole(bytes32 role, address account) external view returns (bool)",
  "function CLUB_ROLE() external view returns (bytes32)",
  "function LEAGUE_ROLE() external view returns (bytes32)",
] as const;

export const LOAN_ESCROW_ABI = [
  "function createLoan(uint256 playerId, address parentClub, address paymentToken, uint256 loanFee, uint256 loanDuration, bool hasOptionToBuy, uint256 optionPrice) external returns (uint256)",
  "function cancelLoan(uint256 loanId) external",
  "function approveLoan(uint256 loanId) external",
  "function rejectLoan(uint256 loanId, string reason) external",
  "function claimLoanFee(uint256 loanId) external",
  "function requestRecall(uint256 loanId) external",
  "function executeRecall(uint256 loanId) external",
  "function settleLoanExpiry(uint256 loanId) external",
  "function exerciseOption(uint256 loanId) external",
  "function withdrawClaimable(address token) external",
  "function getLoan(uint256 loanId) external view returns (tuple(uint256 playerId, address parentClub, address borrowingClub, address paymentToken, uint256 loanFee, uint256 loanStart, uint256 loanExpiry, bool hasOptionToBuy, uint256 optionPrice, uint8 state, uint256 createdAt, uint256 approvedAt, uint256 recallRequestedAt, bool loanFeeClaimed, string rejectionReason))",
  "function getClaimable(address account, address token) external view returns (uint256)",
  "function getActivePlayerLoan(uint256 playerId) external view returns (uint256)",
  "function totalLoans() external view returns (uint256)",
] as const;

export const TRANSFER_WINDOW_ABI = [
  "function isWindowOpen() external view returns (bool)",
  "function getActiveWindow() external view returns (tuple(uint256 id, string label, uint256 opensAt, uint256 closesAt, bool exists))",
  "function scheduleWindow(string label, uint256 opensAt, uint256 closesAt) external returns (uint256)",
  "function totalWindows() external view returns (uint256)",
] as const;

export const ERC20_ABI = [
  "function approve(address spender, uint256 amount) external returns (bool)",
  "function allowance(address owner, address spender) external view returns (uint256)",
  "function balanceOf(address account) external view returns (uint256)",
  "function decimals() external view returns (uint8)",
] as const;
